#!/usr/bin/env bash

for i in $(find . -type f -name "*.py" | grep -v venv | grep -v egg-info | grep -v '\.tox/'); do
  if ! grep -q '^# Copyright' "${i}"; then
    echo "Prepending LICENSE to: ${i}"
    (cat LICENSE | while read line; do
        echo "# ${line}"
    done) | cat - "${i}" > "${i}.new" && mv "${i}.new" "${i}"
  fi
done
